import { z } from "zod";

// Agnostic difficulty levels
export const DifficultySchema = z.enum(["easy", "medium", "hard"]);
export type Difficulty = z.infer<typeof DifficultySchema>;

// Dynamic beat counts depending on dance style or section rhythm
export const BeatCountTypeSchema = z.enum([
  "salsa-8",    // counts 1 to 8
  "bachata-4",  // counts 1 to 4
  "swing-6",    // counts 1 to 6
  "waltz-3",    // counts 1 to 3
  "none"        // silent / no metronome count
]);
export type BeatCountType = z.infer<typeof BeatCountTypeSchema>;

// Untouched Librosa analysis payload (Raw, machine-analyzed data)
export const RawAnalysisSchema = z.object({
  estimatedBpm: z.number(),
  rawBeats: z.array(z.number()), // Array of raw timestamps
  processedAt: z.string().datetime(),
});
export type RawAnalysis = z.infer<typeof RawAnalysisSchema>;

// Section definition (Fully dynamic, agnostic, custom names/emojis)
export const SectionSchema = z.object({
  id: z.string(),
  name: z.string().min(1, "Section name cannot be empty"), // Absolute freedom (e.g., "Trumpet Moña")
  emoji: z.string().default("🎵"),                         // Absolute freedom of emojis
  startTimestamp: z.number().nonnegative(),
  endTimestamp: z.number().nonnegative(),
  focusInstrument: z.string().optional(),
  
  // Agnosticity configuration
  beatCountType: BeatCountTypeSchema.default("none"),
  displayCounts: z.boolean().default(true), // Turns metronome/visual counter ON/OFF
  
  // Section-specific micro-alignment offsets (in milliseconds)
  localOffsetMs: z.number().default(0), // Shifts the beat grid locally for this section
  localBpm: z.number().optional(),      // Overrides global BPM if tempo drifts/changes
});
export type Section = z.infer<typeof SectionSchema>;

// Calibrated Beatmap Structure
export const CalibratedBeatmapSchema = z.object({
  bpm: z.number(),
  beats: z.array(
    z.object({
      timestamp: z.number(),
      beat: z.number().int().positive(), // Modulo applied based on section count style
    })
  ),
  sections: z.array(SectionSchema),
});
export type CalibratedBeatmap = z.infer<typeof CalibratedBeatmapSchema>;

// Unified, Single Agnostic Song Schema
export const AgnosticSongSchema = z.object({
  id: z.string(), // e.g. "song-salsa-pobre-diablo" or "youtube-id"
  title: z.string().min(1, "Title is required"),
  artist: z.string().min(1, "Artist is required"),
  youtubeId: z.string().length(11, "YouTube ID must be exactly 11 characters"),
  youtubeUrl: z.string().url(),
  duration: z.number().positive().optional(),
  difficulty: DifficultySchema,
  isCalibrated: z.boolean().default(false), // Hide from production catalog if false
  
  // Raw data from Librosa (ALWAYS preserved and unchanged)
  rawAnalysis: RawAnalysisSchema,
  
  // Continuous calibration log (whole-song tapping downbeats)
  globalTapLog: z.array(z.number()).default([]), // List of absolute downbeat "1" tap timestamps
  globalReactionDelayMs: z.number().default(200), // Default reaction delay offset
  
  // Calibrated Beatmap (Generated by combining raw analysis + offsets + tap logs)
  calibratedBeatmap: CalibratedBeatmapSchema.optional(),
  
  // Real-time developer drafts to prevent loss during browser crashes
  draftCalibration: z.object({
    lastSavedAt: z.string().datetime(),
    globalTapLogDraft: z.array(z.number()),
    sectionsDraft: z.array(SectionSchema),
    reactionDelayMsDraft: z.number(),
  }).optional(),
});
export type AgnosticSong = z.infer<typeof AgnosticSongSchema>;

// Catalog file schema (only keeps lightweight summary for index loading)
export const CatalogSongSchema = z.object({
  id: z.string(),
  title: z.string(),
  artist: z.string(),
  youtubeId: z.string(),
  bpm: z.number(),
  difficulty: DifficultySchema,
  isCalibrated: z.boolean(),
});
export const CatalogSchema = z.array(CatalogSongSchema);
